In [ ]:
time - 23:00  part 2

# Numpy

Numeric python

In [ ]:
list - collection of different type of elements
array - collection of similar types of elements

In [ ]:
!pip install numpy    - to install numpy

# 1.Creating a vector

In [1]:
import numpy as np

In [4]:
#help(np.array)

np.array?

In [8]:
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [9]:
print(type(v))

<class 'numpy.ndarray'>


In [7]:
print(v)

[1 2 3 4]


In [12]:
v = np.array([[1],[2],[3],[4]])

v

array([[1],
       [2],
       [3],
       [4]])

# 2 - matrix

In [14]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
0th dimension ---->  .

1st dimension ---->  .__________.

2nd dimension ---->  .____|____.

3rd dimension ---->  .____|____.
                         /

4th dimension ?

.
.
.

n dimension

# 3 - Selecting Elements

In [15]:
v = np.array([1,2,3,4,5,6,7])

print(v[0])

1


In [16]:
v[:]          #v[start:end]


array([1, 2, 3, 4, 5, 6, 7])

In [17]:
v[3:6]

array([4, 5, 6])

In [18]:
v[-1]

7

In [19]:
v[-4:-1]

array([4, 5, 6])

In [20]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
matrix[0,0]         #matrix[rows, columns]

1

In [22]:
matrix[1,1]

5

In [23]:
matrix[2,1]

8

In [24]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [26]:
matrix[:,2:3]

array([[3],
       [6],
       [9]])

In [27]:
matrix[0:3,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
matrix[-3:-1,-3:-2]

array([[1],
       [4]])

# 4 - Describe a matrix

In [29]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [30]:
matrix.shape

(4, 3)

In [31]:
matrix.size

12

In [32]:
matrix.ndim

2

# 5 - Max and Min values

In [34]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.max(matrix)

9

In [36]:
np.min(matrix)

1

In [37]:
print(np.max(matrix,axis=0)) #maximum element in each column

[7 8 9]


In [39]:
print(np.max(matrix,axis=1)) #maximum element in each row

[3 6 9]


In [40]:
np.max(matrix,axis=1)[0]

3

# 6 - Mean,Variance,Standard Deviation

In [42]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
print(np.mean(matrix))

5.0


In [44]:
print(np.std(matrix))

2.581988897471611


In [45]:
print(np.var(matrix))

6.666666666666667


# 7 - Reshaping arrays

In [46]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
print(matrix.reshape(9))

[1 2 3 4 5 6 7 8 9]


In [48]:
print(matrix.reshape(9,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [49]:
print(matrix.reshape(9,2))

ValueError: cannot reshape array of size 9 into shape (9,2)

In [50]:
print(matrix.reshape(1,-1))

[[1 2 3 4 5 6 7 8 9]]


In [51]:
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]


# 8 - Transpose a matrix

In [ ]:
what is the real world example of linear algebra?

In [52]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 9 - Determinant and rank

In [54]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
print(np.linalg.det(matrix))

-9.51619735392994e-16


In [57]:
print(np.linalg.matrix_rank(matrix))

2


# 10 - Diagonal

In [58]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
print(matrix.diagonal())

[1 5 9]


In [60]:
print(matrix.diagonal(offset=1))

[2 6]


In [61]:
print(matrix.diagonal(offset=-1))

[4 8]


In [62]:
print(matrix.diagonal(offset=2))

[3]


In [63]:
np.diag(np.rot90(matrix))

array([3, 5, 7])

# 11 - Trace

In [64]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
matrix.trace()        #summation of diagonal is trace

15

# 12 - Dot Product

In [67]:
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix1)
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
print(np.dot(matrix1,matrix2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# 13 - Cross Product

In [69]:
print(matrix1 * matrix2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [70]:
print(np.add(matrix1,matrix2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [71]:
print(np.subtract(matrix1,matrix2))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# 14 - Random Values

In [72]:
np.random.randint(0,11,5)

array([1, 6, 1, 9, 6])

In [73]:
np.random.randint(0,11,9)

array([ 4, 10,  6,  3,  7,  5,  7, 10,  2])

In [74]:
np.random.randint(0,11,9).reshape(3,3)

array([[10,  7,  6],
       [ 2,  3,  2],
       [ 9, 10,  4]])

In [75]:
np.random.seed(1)

np.random.randint(0,11,3)

array([5, 8, 9])

In [77]:
np.random.normal(1.0,2.0,10)

#                mean,std

array([-0.60434568,  0.10224438, -1.21187015, -2.3090309 , -3.72693721,
        3.2706907 , -1.03402827,  2.27472363, -0.71981321,  4.54521526])

In [ ]:
Assignment

Solve chapter 3,4,5 (Numpy folder book)

# Numpy Part 2

# 7 - Selecting element

In [78]:
v = np.array([11,12,13,14,15,16,17])

In [80]:
print(v[0])

11


In [81]:
print(v[5])

16


In [82]:
print(type(v))

<class 'numpy.ndarray'>


In [83]:
#v[start:end]

print(v[3:6])

[14 15 16]


# 8 - Transpose of a matrix

In [84]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 9 - Diagonal

In [86]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
print(matrix.diagonal())

[1 5 9]
